---
- name: Pull docker image of Calculator
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull docker.io/sathvik04/scientific-calculator:latest
      
    - name: running container
      shell: docker run -it -p 3000:3000 -d sathvik04/scientific-calculator:latest